////------------------------------------------------------////
// This file is a part of The Moonshot Project.				
// See LICENSE.txt for license info.						
// File : ParserTests.hpp											
// Author : Pierre van Houtryve								
////------------------------------------------------------//// 
// This file implements the parser tests, generated by parser.def										
////------------------------------------------------------////

#pragma once

#include <vector>
#include <map>
#include <string>
#include <functional>
#include "../Utils/Utils.hpp"
#include "Moonshot/Fox/Parser/Parser.hpp"

namespace Moonshot
{
	class Parser;
}
namespace Moonshot::Tests
{
	// todo : write test class
	class ParserTests
	{
		public:
			ParserTests();

			bool runTests(std::ostream& out,const bool& condensed = false,const bool& show_ast_ = false);

		private:
			bool showAST;
			enum class ParserTestGroups
			{
				// generate the enum for every group
				#define PARSER_TEST_GROUP(STR,ID) ID,
				#include "Moonshot/Tests/def/parser.def"
			};

			enum class ReadMode
			{
				LINES,WHOLE_FILE
			};

			struct IndividualTest
			{
				IndividualTest() = default;
				IndividualTest(const bool& should_pass, const ReadMode& rm, const std::string& fp, std::function<bool(Parser&,const bool&)> fn);

				bool shouldPass;
				std::string filepath;
				ReadMode readmode;
				std::function<bool(Parser&,const bool&)> testfn; // parser instance + print ast if second bool is true
			};

			struct TestGroup
			{
				TestGroup() = default;
				TestGroup(const std::string& nm, const std::vector<IndividualTest> tsts = {});
				std::string name;
				std::vector<IndividualTest> tests;
			};

			bool runAllTestsGroups(std::ostream& out, const bool& condensed);
			bool runTestGroup(const TestGroup& tst,std::ostream& out,const bool& condensed);
			bool runIndividualTest(const IndividualTest& tst,std::ostream& out,const bool& condensed);

			std::map<ParserTestGroups, TestGroup> tests = {
					#define PARSER_TEST_GROUP(Name,ID) {ParserTestGroups::##ID,TestGroup(Name)},
					#include "Moonshot/Tests/def/parser.def"
			};
	};
}


